//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3charts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdventureEntities : DbContext
    {
        public AdventureEntities()
            : base("name=AdventureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<prc_sum_apps_usage_date1_Result> prc_sum_apps_usage_date1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_sum_apps_usage_date1_Result>("prc_sum_apps_usage_date1");
        }
    
        public virtual ObjectResult<prc_combined_vol_Result> prc_combined_vol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_combined_vol_Result>("prc_combined_vol");
        }
    }
}
