//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fixed_top_ups
    {
        public int id { get; set; }
        public Nullable<double> Date { get; set; }
        public Nullable<double> Facebook { get; set; }
        public Nullable<double> TikTok { get; set; }
        public Nullable<double> Google { get; set; }
        public Nullable<double> Twitter { get; set; }
        public Nullable<double> Youtube { get; set; }
        public Nullable<double> iCloud { get; set; }
        public Nullable<double> Amazon { get; set; }
        public Nullable<double> HTTP { get; set; }
        public Nullable<double> Instagram { get; set; }
        public Nullable<double> ZOOM { get; set; }
        public Nullable<double> HTTPS { get; set; }
        public Nullable<double> Netflix { get; set; }
        public Nullable<double> Snapchat { get; set; }
        public Nullable<double> Whatsapp { get; set; }
        public Nullable<double> BOT { get; set; }
        public Nullable<double> ToTok { get; set; }
        public Nullable<double> RTP { get; set; }
        public Nullable<double> iTunes { get; set; }
        public Nullable<double> MicrosoftTeams { get; set; }
    }
}
