//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eprobe_fin_dest
    {
        public System.DateTime DateTime { get; set; }
        public int ProbeID { get; set; }
        public string GameName { get; set; }
        public string ServerLocation { get; set; }
        public string ServerIP { get; set; }
        public double RTT { get; set; }
    }
}
